import { MenuItem, Nutritionist, Challenge, CustomizationRule } from '../types';

export const customizationRules: CustomizationRule[] = [
  {
    id: 'extra-protein',
    type: 'protein',
    label: '+30g Proteína',
    priceModifier: 8.0,
    macroModifier: { protein: 30, calories: 120 },
  },
  {
    id: 'low-carb',
    type: 'carbs',
    label: '-20g Carbohidratos',
    priceModifier: 0,
    macroModifier: { carbs: -20, calories: -80 },
  },
  {
    id: 'extra-fiber',
    type: 'fiber',
    label: '+10g Fibra',
    priceModifier: 3.0,
    macroModifier: { fiber: 10, calories: 20 },
  },
];

export const menuItems: MenuItem[] = [
  {
    id: '1',
    name: 'Power Bowl de Pollo',
    description: 'Pechuga de pollo a la parrilla, quinoa, brócoli, zanahoria y aguacate',
    price: 28.0,
    image: 'https://images.pexels.com/photos/1640777/pexels-photo-1640777.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 520,
      protein: 45,
      carbs: 52,
      fat: 12,
      fiber: 8,
    },
    category: 'Bowls',
    ingredients: ['Pechuga de pollo', 'Quinoa', 'Brócoli', 'Zanahoria', 'Aguacate', 'Aceite de oliva'],
    allergens: [],
    isVegetarian: false,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-1',
    preparationTime: 15,
  },
  {
    id: '2',
    name: 'Wrap de Atún Mediterráneo',
    description: 'Atún, hummus, tomate, lechuga, pepino y aceitunas en tortilla integral',
    price: 24.0,
    image: 'https://es.starkist.com/wp-content/uploads/2014/12/recipes_mediterranean_tuna_wrap.jpg',
    macros: {
      calories: 380,
      protein: 32,
      carbs: 38,
      fat: 10,
      fiber: 6,
    },
    category: 'Wraps',
    ingredients: ['Atún', 'Hummus', 'Tomate', 'Lechuga', 'Pepino', 'Aceitunas', 'Tortilla integral'],
    allergens: ['Gluten', 'Pescado'],
    isVegetarian: false,
    isGlutenFree: false,
    isValidated: true,
    validatedBy: 'nut-1',
    preparationTime: 10,
  },
  {
    id: '3',
    name: 'Ensalada Fitness de Salmón',
    description: 'Salmón ahumado, espinaca, quinoa roja, frutos secos y vinagreta de limón',
    price: 32.0,
    image: 'https://images.pexels.com/photos/1059905/pexels-photo-1059905.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 420,
      protein: 38,
      carbs: 28,
      fat: 18,
      fiber: 5,
    },
    category: 'Ensaladas',
    ingredients: ['Salmón ahumado', 'Espinaca', 'Quinoa roja', 'Almendras', 'Nueces', 'Vinagreta de limón'],
    allergens: ['Pescado', 'Frutos secos'],
    isVegetarian: false,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-2',
    preparationTime: 12,
  },
  {
    id: '4',
    name: 'Bowl Vegano de Garbanzos',
    description: 'Garbanzos especiados, arroz integral, kale, pimiento, tahini',
    price: 22.0,
    image: 'https://images.pexels.com/photos/1640772/pexels-photo-1640772.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 480,
      protein: 18,
      carbs: 68,
      fat: 14,
      fiber: 12,
    },
    category: 'Bowls',
    ingredients: ['Garbanzos', 'Arroz integral', 'Kale', 'Pimiento', 'Tahini', 'Comino', 'Pimentón'],
    allergens: ['Sésamo'],
    isVegetarian: true,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-2',
    preparationTime: 18,
  },
  {
    id: '5',
    name: 'Pechuga al Limón con Camote',
    description: 'Pechuga de pollo con limón, camote asado y ejotes al vapor',
    price: 26.0,
    image: 'https://images.pexels.com/photos/2338407/pexels-photo-2338407.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 440,
      protein: 42,
      carbs: 48,
      fat: 8,
      fiber: 7,
    },
    category: 'Platos Calientes',
    ingredients: ['Pechuga de pollo', 'Limón', 'Camote', 'Ejotes', 'Ajo', 'Hierbas'],
    allergens: [],
    isVegetarian: false,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-1',
    preparationTime: 20,
  },
  {
    id: '6',
    name: 'Bowl de Carne Magra y Batata',
    description: 'Lomo fino, batata asada, espinaca y salsa chimichurri light',
    price: 34.0,
    image: 'https://images.pexels.com/photos/1640770/pexels-photo-1640770.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 560,
      protein: 48,
      carbs: 55,
      fat: 15,
      fiber: 9,
    },
    category: 'Bowls',
    ingredients: ['Lomo fino', 'Batata', 'Espinaca', 'Chimichurri light', 'Ajo', 'Perejil'],
    allergens: [],
    isVegetarian: false,
    isGlutenFree: true,
    isValidated: false,
    preparationTime: 22,
  },
  {
    id: '7',
    name: 'Wrap de Pollo y Aguacate',
    description: 'Pollo desmenuzado, aguacate, lechuga, tomate y yogurt griego en tortilla',
    price: 23.0,
    image: 'https://vitalplus.com.co/cdn/shop/articles/Wraps-de-Pollo-y-Aguacate.jpg?v=1692044544',
    macros: {
      calories: 410,
      protein: 35,
      carbs: 36,
      fat: 14,
      fiber: 6,
    },
    category: 'Wraps',
    ingredients: ['Pollo', 'Aguacate', 'Lechuga', 'Tomate', 'Yogurt griego', 'Tortilla integral'],
    allergens: ['Gluten', 'Lácteos'],
    isVegetarian: false,
    isGlutenFree: false,
    isValidated: true,
    validatedBy: 'nut-2',
    preparationTime: 12,
  },
  {
    id: '8',
    name: 'Ensalada Protein Power',
    description: 'Mix de lechugas, pollo, huevo, garbanzos, tomate cherry y aderezo de mostaza',
    price: 27.0,
    image: 'https://images.pexels.com/photos/1213710/pexels-photo-1213710.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 390,
      protein: 40,
      carbs: 25,
      fat: 12,
      fiber: 8,
    },
    category: 'Ensaladas',
    ingredients: ['Lechuga', 'Pollo', 'Huevo', 'Garbanzos', 'Tomate cherry', 'Mostaza Dijon'],
    allergens: ['Huevo', 'Mostaza'],
    isVegetarian: false,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-1',
    preparationTime: 10,
  },
  {
    id: '9',
    name: 'Bowl Asiático de Tofu',
    description: 'Tofu marinado, arroz jazmín, edamame, col morada y salsa teriyaki sin azúcar',
    price: 24.0,
    image: 'https://images.pexels.com/photos/1640771/pexels-photo-1640771.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 460,
      protein: 22,
      carbs: 58,
      fat: 16,
      fiber: 10,
    },
    category: 'Bowls',
    ingredients: ['Tofu', 'Arroz jazmín', 'Edamame', 'Col morada', 'Zanahoria', 'Salsa teriyaki'],
    allergens: ['Soja'],
    isVegetarian: true,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-2',
    preparationTime: 16,
  },
  {
    id: '10',
    name: 'Pavo a la Plancha con Verduras',
    description: 'Pechuga de pavo, calabacín, berenjena, pimiento y arroz integral',
    price: 29.0,
    image: 'https://images.pexels.com/photos/262959/pexels-photo-262959.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 450,
      protein: 44,
      carbs: 46,
      fat: 9,
      fiber: 8,
    },
    category: 'Platos Calientes',
    ingredients: ['Pechuga de pavo', 'Calabacín', 'Berenjena', 'Pimiento', 'Arroz integral', 'Hierbas'],
    allergens: [],
    isVegetarian: false,
    isGlutenFree: true,
    isValidated: false,
    preparationTime: 20,
  },
  {
    id: '11',
    name: 'Hamburguesa Fitness de Pavo',
    description: 'Hamburguesa de pavo magro, pan integral, aguacate, tomate y cebolla caramelizada',
    price: 26.0,
    image: 'https://images.pexels.com/photos/1639557/pexels-photo-1639557.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 480,
      protein: 38,
      carbs: 42,
      fat: 16,
      fiber: 7,
    },
    category: 'Platos Calientes',
    ingredients: ['Pavo molido', 'Pan integral', 'Aguacate', 'Tomate', 'Cebolla', 'Lechuga'],
    allergens: ['Gluten'],
    isVegetarian: false,
    isGlutenFree: false,
    isValidated: true,
    validatedBy: 'nut-1',
    preparationTime: 18,
  },
  {
    id: '12',
    name: 'Bowl Mexicano de Frijoles',
    description: 'Frijoles negros, arroz integral, pico de gallo, aguacate, queso fresco y jalapeños',
    price: 21.0,
    image: 'https://images.pexels.com/photos/1640773/pexels-photo-1640773.jpeg?auto=compress&cs=tinysrgb&w=800',
    macros: {
      calories: 490,
      protein: 20,
      carbs: 72,
      fat: 14,
      fiber: 16,
    },
    category: 'Bowls',
    ingredients: ['Frijoles negros', 'Arroz integral', 'Tomate', 'Cebolla', 'Aguacate', 'Queso fresco', 'Jalapeño'],
    allergens: ['Lácteos'],
    isVegetarian: true,
    isGlutenFree: true,
    isValidated: true,
    validatedBy: 'nut-2',
    preparationTime: 15,
  },
];

export const nutritionists: Nutritionist[] = [
  {
    id: 'nut-1',
    name: 'Dra. Maria Linares García',
    photo: 'https://s3-sa-east-1.amazonaws.com/doctoralia.pe/doctor/a03c5b/a03c5b280de4ec780edebc6d5b627a59_220_square.jpg',
    license: 'CNP 12345',
    bio: 'Nutricionista deportiva con 10 años de experiencia. Especializada en nutrición para atletas de alto rendimiento.',
    specialties: ['Nutrición Deportiva', 'Pérdida de Grasa', 'Ganancia Muscular'],
  },
  {
    id: 'nut-2',
    name: 'Lic. Carlos Ramírez',
    photo: 'https://clinicabiozellen.cl/wp-content/uploads/elementor/thumbs/Nutricionista-Alvaro-Parra-plytppxpcw99hjuvgq9vov0p4nlpzy3yv2i1hq4hkw.png',
    license: 'CNP 67890',
    bio: 'Nutricionista clínico especializado en planes alimenticios personalizados y nutrición funcional.',
    specialties: ['Nutrición Funcional', 'Dietas Plant-Based', 'Metabolismo'],
  },
];

export const challenges: Challenge[] = [
  {
    id: 'ch-1',
    title: 'Desafío 30 Días de Proteína',
    description: 'Consume al menos 120g de proteína diaria durante 30 días consecutivos',
    goal: 30,
    current: 12,
    reward: 500,
    endsAt: new Date('2025-10-31'),
    type: 'monthly',
  },
  {
    id: 'ch-2',
    title: 'Come Saludable Esta Semana',
    description: 'Ordena al menos 5 platillos de VITANZA esta semana',
    goal: 5,
    current: 2,
    reward: 100,
    endsAt: new Date('2025-10-07'),
    type: 'weekly',
  },
  {
    id: 'ch-3',
    title: 'Meta Diaria de Calorías',
    description: 'Mantén tu consumo calórico dentro de tu objetivo hoy',
    goal: 1,
    current: 0,
    reward: 20,
    endsAt: new Date('2025-10-01'),
    type: 'daily',
  },
];
